#!/usr/bin/env bash

SCRIPT_LOCATION=$(readlink -f $0)
FOLDER=$(dirname $SCRIPT_LOCATION)
GITHUB_USERNAME=$(grep GITHUB_USERNAME $FOLDER/.env | cut -d '=' -f2)
GITHUB_BEARER_TOKEN=$(grep GITHUB_BEARER_TOKEN $FOLDER/.env | cut -d '=' -f2)

PYTHON_SCRIPT=$FOLDER/response_handler.py

query_response=$(curl -s -u $GITHUB_USERNAME:$GITHUB_BEARER_TOKEN https://api.github.com/notifications)

python3 $PYTHON_SCRIPT $query_response

